security:
    basic:
        enabled: false # turn-off securing our application endpoints

management:
    security:
        enabled: false # turn-off securing the actuator endpoints

logging:
    pattern:
        console: "%-5level %logger{36} : %msg%n"
    level:
        root: WARN
        io:
            pivotal: DEBUG
